### ISSUE TITLE
Manually inject plugin dependencies is very hard

### ISSUE THREAD

**Issue by jean-helsinki** [ec4j/editorconfig-gradle-plugin#10]
Manually inject plugin dependencies to root project broke custom repository layout - all dependencies be search on maven central.

https://github.com/ec4j/editorconfig-gradle-plugin/blob/master/src/main/java/org/ec4j/gradle/EditorconfigGradlePlugin.java#L39

**Comment by ppalaga** [comment]
Thanks for the report, but I am missing the following details:

1. A project where the issue can be reproduced, ideally under https://github.com/ec4j/editorconfig-gradle-plugin/tree/master/src/test/projects in form of a pull request.

2. What behavior do you expect?

3. What actually happens?

**Comment by nkiesel** [comment]
I just ran into the same problem.  We use a local artifactory server to serve our jars and gradle plugins to have better control over which versions our developers can use.  Our build broke after I added this plugin to gradle.  Root cause is that we use javax.jms:jms:1.1 (I know,  ancient) and that the jar for this is - for licensing reasons - not available on mavencentral (but is available in our local repo).  This plugin injects mavencentral and gradle then finds the pom file there and thus insists on getting the jar file from mavencentral as well.

It would be much nicer if the location from where to find the linter would be left to the user of this plugin instead of force-feeding mavencentral.

**Comment by ppalaga** [comment]
I admit I am a Gradle noob. I'd be thankful for pointers how other Gradle plugins solve this kind of problems.

**Comment by nkiesel** [comment]
Minimally, could you not just ask users to add this dependency explicitly?  A bit more inconvenient, but sidesteps this problem.

The bigger solution would be to support a configuration block where the linter is configured in build.gradle(.kts)?  This then would also allow to remove the hard-coded (and repeated) linter version.
